# ==========================================
# CONFIGURACOES DE DESENVOLVIMENTO
# ==========================================

spring.application.name=agendamento

# ==========================================
# CONFIGURACOES DO BANCO DE DADOS LOCAL
# ==========================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/agendamento
spring.datasource.url=jdbc:postgresql://postgres:5432/agendamento_dev
spring.datasource.username=postgres
spring.datasource.password=Vi1106@
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# CONFIGURACOES DO JPA/HIBERNATE
# ==========================================
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACOES DE PAGINACAO
# ==========================================
spring.data.web.pageable.default-page-size=7
spring.data.web.pageable.max-page-size=100

# ==========================================
# CONFIGURACOES DE SEGURANCA JWT
# ==========================================
security.jwt.secret=Z4c#Wp9dL1!qTe7R@o6Mz&VuKg0XzC^yb
security.jwt.expiration=86400000

# ==========================================
# CONFIGURACOES DO SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACOES DE LOGGING
# ==========================================
logging.level.org.springframework.web=DEBUG
logging.level.br.com.sasaki.solution.agendamento=DEBUG
logging.level.org.springframework.security=DEBUG

# ==========================================
# CONFIGURACOES DE MONITORAMENTO (DEV)
# ==========================================
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.info.env.enabled=true