spring.application.name=agendamento

spring.datasource.url=jdbc:postgresql://localhost:5432/agendamento
spring.datasource.username=postgres
spring.datasource.password=Vi1106@
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=dev
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
